DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): api.openweathermap.org:80
DEBUG:urllib3.connectionpool:http://api.openweathermap.org:80 "GET /data/2.5/weather?lat=41.899139&lon=12.473311&units=metric&appid=550617cb3af649e1d6729a3f78b24e17 HTTP/1.1" 200 462
INFO:root:Eccezione ore: 2021-03-25 11:45:32.293814
ERROR:root:(<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x7f803688d880>)
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): api.openweathermap.org:80
DEBUG:urllib3.connectionpool:http://api.openweathermap.org:80 "GET /data/2.5/weather?lat=45.3397&lon=16.9787&units=metric&appid=550617cb3af649e1d6729a3f78b24e17 HTTP/1.1" 200 453
INFO:root:Eccezione ore: 2021-03-25 11:45:32.621759
ERROR:root:(<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x7f803688d080>)
